services:
  backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./scamscanner:/app/scamscanner
      - ./scamscan.db:/app/scamscan.db
    env_file:
      - .env.local
    command: uvicorn scamscanner.app:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: .
      dockerfile: frontend.dockerfile
      args:
        VITE_API_BASE_URL: http://backend:8000
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - frontend/.env
    depends_on:
      - backend

networks:
  default:
    driver: bridge